
[dependencies]
astropy = ">=7.1.0,<8"
astroquery = ">=0.4.10,<0.5"
corner = ">=2.2.3,<3"
emcee = ">=3.1.6,<4"
jupyter = ">=1.1.1,<2"
lmfit = ">=1.3.3,<2"
matplotlib = ">=3.10.3,<4"
multiprocess = ">=0.70.18,<0.71"
numpy = ">=2.3.1,<3"
pandas = ">=2.3.0,<3"
python = ">=3.13.5,<3.14"
scipy = ">=1.16.0,<2"
tqdm = ">=4.67.1,<5"

[pypi-dependencies]
ppxf = ">=9.4.2, <10"
pyastronomy = ">=0.20.0, <0.21"
sfdmap2 = ">=0.2.2.post3, <0.3"

[tasks]

[workspace]
channels = ["conda-forge"]
name = "PyQSOFit"
platforms = ["linux-64", "win-64", "osx-arm64"]
